#ifndef HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGBOXA_H
#define HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGBOXA_H

// Generated by scripts/mm_to_header.py -- do not edit by hand.
// Convex QP  min 0.5 x^T P x + q^T x  s.t.  l <= A x <= u.
// P is stored dense row-major (symmetric); A is dense row-major.

#include <array>
#include <limits>

namespace argmin::mm_data::agboxa
{
inline constexpr double inf = std::numeric_limits<double>::infinity();
inline constexpr int n = 2;
inline constexpr int m = 2;
inline constexpr bool has_optimum = true;
inline constexpr double optimum = -8;
inline constexpr char label[] = "AGBOXA";
inline constexpr std::array<double, 4> P = { 2, 0, 0, 4 };
inline constexpr std::array<double, 2> q = { 3, -10 };
inline constexpr std::array<double, 4> A = { 1, 0, 0, 1 };
inline constexpr std::array<double, 2> l = { 0, 0 };
inline constexpr std::array<double, 2> u = { inf, 1 };
}

#endif
