#ifndef HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGBOXB_H
#define HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGBOXB_H

// Generated by scripts/mm_to_header.py -- do not edit by hand.
// Convex QP  min 0.5 x^T P x + q^T x  s.t.  l <= A x <= u.
// P is stored dense row-major (symmetric); A is dense row-major.

#include <array>
#include <limits>

namespace argmin::mm_data::agboxb
{
inline constexpr double inf = std::numeric_limits<double>::infinity();
inline constexpr int n = 8;
inline constexpr int m = 8;
inline constexpr bool has_optimum = true;
inline constexpr double optimum = -4.1966517857142858;
inline constexpr char label[] = "AGBOXB";
inline constexpr std::array<double, 64> P = { 2, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 14, 0, 0, 0, 0, 0, 0, 0, 0, 16 };
inline constexpr std::array<double, 8> q = { -3.5, 2.5, -1.5, 0.5, 0.5, -1.5, 2.5, -3.5 };
inline constexpr std::array<double, 64> A = { 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1 };
inline constexpr std::array<double, 8> l = { -1, -1, -1, -1, -1, -1, -1, -1 };
inline constexpr std::array<double, 8> u = { 1, 1, 1, 1, 1, 1, 1, 1 };
}

#endif
