#ifndef HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGEQB_H
#define HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGEQB_H

// Generated by scripts/mm_to_header.py -- do not edit by hand.
// Convex QP  min 0.5 x^T P x + q^T x  s.t.  l <= A x <= u.
// P is stored dense row-major (symmetric); A is dense row-major.

#include <array>
#include <limits>

namespace argmin::mm_data::ageqb
{
inline constexpr double inf = std::numeric_limits<double>::infinity();
inline constexpr int n = 5;
inline constexpr int m = 2;
inline constexpr bool has_optimum = true;
inline constexpr double optimum = 2.8701388888888886;
inline constexpr char label[] = "AGEQB";
inline constexpr std::array<double, 25> P = { 5, 0.5, 0.5, 0.5, 0.5, 0.5, 5, 0.5, 0.5, 0.5, 0.5, 0.5, 5, 0.5, 0.5, 0.5, 0.5, 0.5, 5, 0.5, 0.5, 0.5, 0.5, 0.5, 5 };
inline constexpr std::array<double, 5> q = { 1, -1, 2, -2, 0.5 };
inline constexpr std::array<double, 10> A = { 1, 1, 1, 1, 1, 1, -1, 0, 0, 0 };
inline constexpr std::array<double, 2> l = { 2, 0.5 };
inline constexpr std::array<double, 2> u = { 2, 0.5 };
}

#endif
