#ifndef HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGEQA_H
#define HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGEQA_H

// Generated by scripts/mm_to_header.py -- do not edit by hand.
// Convex QP  min 0.5 x^T P x + q^T x  s.t.  l <= A x <= u.
// P is stored dense row-major (symmetric); A is dense row-major.

#include <array>
#include <limits>

namespace argmin::mm_data::ageqa
{
inline constexpr double inf = std::numeric_limits<double>::infinity();
inline constexpr int n = 3;
inline constexpr int m = 1;
inline constexpr bool has_optimum = true;
inline constexpr double optimum = -2;
inline constexpr char label[] = "AGEQA";
inline constexpr std::array<double, 9> P = { 4, 1, 0, 1, 3, 1, 0, 1, 2 };
inline constexpr std::array<double, 3> q = { -1, -2, -3 };
inline constexpr std::array<double, 3> A = { 1, 1, 1 };
inline constexpr std::array<double, 1> l = { 1 };
inline constexpr std::array<double, 1> u = { 1 };
}

#endif
