#ifndef HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGINEQA_H
#define HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGINEQA_H

// Generated by scripts/mm_to_header.py -- do not edit by hand.
// Convex QP  min 0.5 x^T P x + q^T x  s.t.  l <= A x <= u.
// P is stored dense row-major (symmetric); A is dense row-major.

#include <array>
#include <limits>

namespace argmin::mm_data::agineqa
{
inline constexpr double inf = std::numeric_limits<double>::infinity();
inline constexpr int n = 2;
inline constexpr int m = 3;
inline constexpr bool has_optimum = true;
inline constexpr double optimum = -1.9375;
inline constexpr char label[] = "AGINEQA";
inline constexpr std::array<double, 4> P = { 1, 0, 0, 1 };
inline constexpr std::array<double, 2> q = { -1, -2 };
inline constexpr std::array<double, 6> A = { 1, 1, 1, 0, 0, 1 };
inline constexpr std::array<double, 3> l = { -inf, 0, 0 };
inline constexpr std::array<double, 3> u = { 1.5, inf, inf };
}

#endif
