#ifndef HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGMIXA_H
#define HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGMIXA_H

// Generated by scripts/mm_to_header.py -- do not edit by hand.
// Convex QP  min 0.5 x^T P x + q^T x  s.t.  l <= A x <= u.
// P is stored dense row-major (symmetric); A is dense row-major.

#include <array>
#include <limits>

namespace argmin::mm_data::agmixa
{
inline constexpr double inf = std::numeric_limits<double>::infinity();
inline constexpr int n = 4;
inline constexpr int m = 5;
inline constexpr bool has_optimum = true;
inline constexpr double optimum = -0.86875000000000036;
inline constexpr char label[] = "AGMIXA";
inline constexpr std::array<double, 16> P = { 6, 1, 1, 1, 1, 6, 1, 1, 1, 1, 6, 1, 1, 1, 1, 6 };
inline constexpr std::array<double, 4> q = { -3, 1, -2, 0.5 };
inline constexpr std::array<double, 20> A = { 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 };
inline constexpr std::array<double, 5> l = { 1, -5, -5, -5, -5 };
inline constexpr std::array<double, 5> u = { 1, 5, 5, 5, 5 };
}

#endif
