#ifndef HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGRNGA_H
#define HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_AGRNGA_H

// Generated by scripts/mm_to_header.py -- do not edit by hand.
// Convex QP  min 0.5 x^T P x + q^T x  s.t.  l <= A x <= u.
// P is stored dense row-major (symmetric); A is dense row-major.

#include <array>
#include <limits>

namespace argmin::mm_data::agrnga
{
inline constexpr double inf = std::numeric_limits<double>::infinity();
inline constexpr int n = 3;
inline constexpr int m = 4;
inline constexpr bool has_optimum = true;
inline constexpr double optimum = 0.5;
inline constexpr char label[] = "AGRNGA";
inline constexpr std::array<double, 9> P = { 3, 0, 0, 0, 3, 0, 0, 0, 3 };
inline constexpr std::array<double, 3> q = { 0, 0, 0 };
inline constexpr std::array<double, 12> A = { 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1 };
inline constexpr std::array<double, 4> l = { 1, -10, -10, -10 };
inline constexpr std::array<double, 4> u = { 2, 10, 10, 10 };
}

#endif
