#ifndef HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_MM_PROBLEMS_H
#define HPP_GUARD_ARGMIN_TESTS_UNIT_MM_DATA_MM_PROBLEMS_H

// Generated by scripts/mm_to_header.py -- do not edit by hand.
// Aggregates every converted problem header; pair with
// mm_problems.inc for X-macro registration.

#include "agboxa.h"
#include "agboxb.h"
#include "ageqa.h"
#include "ageqb.h"
#include "agineqa.h"
#include "agmixa.h"
#include "agrnga.h"

#endif
